name: Node.js Continuous Delivery

on:
  push:
    branches:
      - master

permissions:
  contents: write
  repository-projects: write

jobs:
  Deploy-Jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 21.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install --production

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Set up Environment Variables
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project in Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project in Vercel
        run: |
          # Capture the deployment URL in a file
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          # Read the URL and store it in a GitHub environment variable
          DEPLOYMENT_URL=$(cat deployment-url.txt)
          echo "DEPLOYMENT_URL=${DEPLOYMENT_URL}" >> $GITHUB_ENV
          rm deployment-url.txt

      - name: Update GitHub repository description with Vercel URL
        run: |
          # Escape special characters in the deployment URL
          DEPLOY_URL=$(echo "$DEPLOYMENT_URL" | sed 's/[\/&]/\\&/g')
          DESCRIPTION="Deployment URL Vercel: ${DEPLOY_URL}"

          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${REPO_NAME}" \
            -d "{\"description\":\"${DESCRIPTION}\"}"
 